ALTER TABLE E2E_DW_UAT.ADOPTION SET COMMENT = "Adoption tables contains project & experiment that are selected for further process";
create or replace view E2E_DEV_PILOT_DB.E2E_DW.CURRCNVRSN_VW(
	FROMCURRID,
	TOCURRID,
	EXCHANGERATE_OLD,
	EXCHANGERATE,
	FROM_DT,
	TO_DT,
	CURRCODE COMMENT 'CURRENCY CONVERSION RATE VIEW CREATED WITH REPETELY R1' 
) as

SELECT FROMCURRID
	,TOCURRID
    ,((EXCHANGERATE / RATIO_FROM) * RATIO_TO )  AS EXCHANGERATE_OLD
	,((EXCHANGERATE / RATIO_FROM) * RATIO_TO )  * FactorValueNumber AS EXCHANGERATE
	,DATE AS FROM_DT
	,NVL(LEAD(DATE - 1, 1) OVER (
			PARTITION BY FROMCURRID
			,TOCURRID ORDER BY DATE
			), '9999-12-31') AS TO_DT
     ,CURRCODE
FROM (
	SELECT
         CURRCNV.FROMCURRID
		,CURRCNV.TOCURRID
		,CURRCNV.EXCHANGERATE
		,CAL.DATE
		,CURRCNV.EXCHANGERATETYPEID
		,CUR_RT.RATIO_FROM
		,CUR_RT.RATIO_TO
        ,CUR.CURRCODE 
        ,NVL(CDP.FactorValueNumber ,1) AS FactorValueNumber
	FROM E2E_DW.CURRCNVRSN CURRCNV
	LEFT OUTER JOIN E2E_DW.CURRCNVRSN_RATIO CUR_RT ON (
			CURRCNV.FROMCURRID = CUR_RT.FROM_CURRID
			AND CURRCNV.TOCURRID = CUR_RT.TO_CURRID
			AND CURRCNV.EXCHANGERATETYPEID = CUR_RT.EXCHANGERATETYPEID
			)
	JOIN E2E_DW.CALENDAR CAL ON (CURRCNV.EXCHANGEEFFECTIVDATEID = CAL.DATEID)
  
    JOIN E2E_DW.CURR CUR ON (CURRCNV.FROMCURRID = CUR.CURRID)
    
    LEFT JOIN E2E_DW.CurrDecimalPlace CDP ON (CUR.CURRCODE = CDP.SystemCurrKeyCode )
  
	 WHERE CURRCNV.EXCHANGERATETYPEID = (
			SELECT CURREXCHANGERATETYPEID
			FROM E2E_DW.CURREXCHANGERATETYPE
			WHERE CURREXCHANGERATETYPE = '001W'
			)
  
    --AND CURRCODE  in ('IDR') 
    -- AND SystemCurrKeyCode  in ('JPY','KUD','KRW','VND') 
	);
create or replace view E2E_DW_UAT.CURRCNVRSN_VW(
	FROMCURRID,
	TOCURRID,
	EXCHANGERATE ,
	FROM_DT,
	TO_DT COMMENT 'CURRENCY CONVERSION RATE VIEW CREATED WITH REPETELY R1'  
) as 
SELECT 
                 FROMCURRID
                ,TOCURRID
                ,EXCHANGERATE
                 , DATE AS FROM_DT
                ,NVL(LEAD(DATE-1,1) OVER(PARTITION BY FROMCURRID, TOCURRID ORDER BY DATE ),'9999-12-31')  AS TO_DT 
FROM ( SELECT FROMCURRID, TOCURRID,EXCHANGERATE,DATE
                                FROM CURRCNVRSN CURR
                                     ,CALENDAR CAL 
                                WHERE CURR.EXCHANGEEFFECTIVDATEID = CAL.DATEID
                                  AND EXCHANGERATETYPEID  = (SELECT CURREXCHANGERATETYPEID   FROM CURREXCHANGERATETYPE WHERE CURREXCHANGERATETYPE ='001S'
                                  )         );
